### ISSUE TITLE
F-Droid failed to build

### ISSUE THREAD

**Issue by linsui** [subins2000/manglish#11]
```
Execution failed for task ':app:mergeReleaseResources'.
> Could not list contents of '/home/vagrant/build/subins2000.manglish/app/src/main/res/mipmap-xxhdpi/overlay_button.png'. Couldn't follow symbolic link.
```

Could you please take a look? Thanks!

**Comment by subins2000** [comment]
Thank you for reporting @linsui. I'll correct this and force push my latest 7.0 tag. Will that work out ?

**Comment by linsui** [comment]
Yes, thanks!

**Comment by subins2000** [comment]
Done! Forced push to the latest version tag: https://github.com/subins2000/manglish/releases/tag/7.0

Please lmk if it works out
