### ISSUE TITLE
[Bug Report] The keyboard does not disappear when you switch to another tab (About Section).

### ISSUE THREAD

**Issue by eraydurmus** [subins2000/manglish#7]
**Actual behavior**
I can write when I want to write something, but the keyboard does not disappear when I switch to another tab.

**Expected behavior**
The keyboard should disappear automatically when you switch to another tab.

**Steps to reproduce the behavior:**

1. Open the app.
2. Write something in the empty field.
3. Switch to another tab (About Section).
4. You will see that the keyboard doesn't disappear automatically and you can still write in the field.

Phone info:

• ROM: MIUI Global 10.3.6
• Android Version: Android 9.0
App version: 3.0 (latest)

**Recording Of The Bug**
![GlossySlipperyIntermediateegret-size_restricted](https://user-images.githubusercontent.com/34961616/60598389-4db72380-9db5-11e9-8209-0153ef2a9ec6.gif)

**Comment by subins2000** [comment]
Thank you for the detailed report. This has been fixed in version 4 released yesterday thanks to #6
